export const allBounties = state => state.bounties.all
export const allCareers = state => state.careers.all
export const allMedia = state => state.media.all
export const allPeople = state => state.people.all
export const allPosts = state => state.posts.all
export const allPresentations = state => state.presentations.all
export const allSoftware = state => state.software
export const config = state => state.config
export const timers = state => state.timers
