<!--THIS FILE IS GENERATED BY `./blog/build.js` DO NOT EDIT HERE-->
<template><div id="page-blog-index">
  <section id="section-top"><div class="section-container">
  <div class="article-wrapper" id="blog-index">
    <h1><i class="fa fa-rss"></i> Tendermint Blog</h1>
    <p>Learn about what we&rsquo;re working on, right this moment. <a href="/static/feed.xml">Subscribe via RSS</a></p>
  </div></section>
<section class="section-default section-flush"><div class="section-container"><div class="section-content">
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/tendermint-from-then-to-now'">
    <header class="li-article-header"><h2>Tendermint: from Then to Now</h2></header>
    <div class="li-article-content">The history of Tendermint, and information on the latest release and more</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on September 17, 2016</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/on-thedao-and-proof-of-stake-governance'">
    <header class="li-article-header"><h2>On TheDAO and Proof-of-Stake Governance</h2></header>
    <div class="li-article-content"></div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on June 21, 2016</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/a-critique-of-merkle-s-dao-democracy-making-it-reliable'">
    <header class="li-article-header"><h2>A Critique of Merkle's DAO Democracy: Making it Reliable</h2></header>
    <div class="li-article-content">A critique of the subsection of the new DAO paper by Merkle, specifically of the section entitled 'Making it Reliable'</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on June 6, 2016</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/tmsp-the-tendermint-socket-protocol'">
    <header class="li-article-header"><h2>TMSP: The Tendermint Socket Protocol</h2></header>
    <div class="li-article-content">TMSP lets you create blockchain application easily in any languge.  This post describes the motivation behind TMSP and links to tutorials.</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on December 19, 2015</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/tendermint-for-fast-settlement'">
    <header class="li-article-header"><h2>Tendermint for Fast Settlement</h2></header>
    <div class="li-article-content">Blockchains provide new opportunities in fast settlement</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on October 3, 2015</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/tendermint-vs-pbft'">
    <header class="li-article-header"><h2>Tendermint vs PBFT</h2></header>
    <div class="li-article-content">Tendermint is a variant of PBFT; similarities and differences explained</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on October 3, 2015</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/cases-for-tendermint'">
    <header class="li-article-header"><h2>Cases for Tendermint</h2></header>
    <div class="li-article-content">Why you should build on Tendermint, and whether to use the EVM</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on September 13, 2015</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/sidechains-without-pegging'">
    <header class="li-article-header"><h2>Sidechains without Pegging</h2></header>
    <div class="li-article-content">Sidechains is more than one-way or two-way pegging, and beyond Bitcoin Maximalism.</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on November 25, 2014</div>
  </div>
</div>
<div class="li-article">
  <router-link class="li-article-link" :to="'/blog/the-security-of-cryptocurrency-protocols'">
    <header class="li-article-header"><h2>The Security of Cryptocurrency Protocols</h2></header>
    <div class="li-article-content">Security analysis of cryptocurrency protocols is complicated by incentive-alignment and extrinsic factors.  A look at more robust security guarantees</div>
  </router-link>
  <div class="li-article-meta">
    <div class="date">Posted on November 19, 2014</div>
  </div>
</div>
  </div></div></section>
</div></template>
<script>
export default {
  head: {
    title: {
      inner: 'Blog'
    }
  }
}
</script>
