<!--THIS FILE IS GENERATED BY `./blog/build.js` DO NOT EDIT HERE-->
<template><div id="page-blog-index">
  <div class="header-padding"></div>
  <div class="article-wrapper" id="blog-index">
    <h1>Tendermint Blog</h1>
    <div class="subtitle"><a href="/static/feed.xml">Subscribe</a> for the latest updates.</div>
    <router-link class="article-link" :to="'/blog/cases-for-tendermint'">
      <div class="article-title">Cases for Tendermint</div>
      <div class="article-excerpt">Why you should build on Tendermint, and whether to use the EVM</div>
      <div class="article-date">Posted on September 13, 2015</div>
    </router-link>
  </div><!--article-wrapper-->
</div></template>
<script>
export default {
  head: {
    title: {
      inner: 'Blog'
    }
  }
}
</script>
