// THESE BLOG ROUTES ARE GENERATED BY `./blog/build.js` DO NOT EDIT HERE-->
import BlogTendermintFromThenToNow from '../components/blog/tendermint-from-then-to-now.vue'
import BlogOnThedaoAndProofOfStakeGovernance from '../components/blog/on-thedao-and-proof-of-stake-governance.vue'
import BlogACritiqueOfMerkleSDaoDemocracyMakingItReliable from '../components/blog/a-critique-of-merkle-s-dao-democracy-making-it-reliable.vue'
import BlogTmspTheTendermintSocketProtocol from '../components/blog/tmsp-the-tendermint-socket-protocol.vue'
import BlogTendermintForFastSettlement from '../components/blog/tendermint-for-fast-settlement.vue'
import BlogTendermintVsPbft from '../components/blog/tendermint-vs-pbft.vue'
import BlogCasesForTendermint from '../components/blog/cases-for-tendermint.vue'
import BlogSidechainsWithoutPegging from '../components/blog/sidechains-without-pegging.vue'
import BlogTheSecurityOfCryptocurrencyProtocols from '../components/blog/the-security-of-cryptocurrency-protocols.vue'
const blogRoutes = [
  { path: '/blog/tendermint-from-then-to-now', component: BlogTendermintFromThenToNow },
  { path: '/blog/on-thedao-and-proof-of-stake-governance', component: BlogOnThedaoAndProofOfStakeGovernance },
  { path: '/blog/a-critique-of-merkle-s-dao-democracy-making-it-reliable', component: BlogACritiqueOfMerkleSDaoDemocracyMakingItReliable },
  { path: '/blog/tmsp-the-tendermint-socket-protocol', component: BlogTmspTheTendermintSocketProtocol },
  { path: '/blog/tendermint-for-fast-settlement', component: BlogTendermintForFastSettlement },
  { path: '/blog/tendermint-vs-pbft', component: BlogTendermintVsPbft },
  { path: '/blog/cases-for-tendermint', component: BlogCasesForTendermint },
  { path: '/blog/sidechains-without-pegging', component: BlogSidechainsWithoutPegging },
  { path: '/blog/the-security-of-cryptocurrency-protocols', component: BlogTheSecurityOfCryptocurrencyProtocols }
]

// STATIC ROUTES
import VueRouter from 'vue-router'

import PageIndex from '../components/pages/Index.vue'
import PageIntro from '../components/pages/Intro.vue'
import PageDocs from '../components/pages/Docs.vue'
import PageCommunity from '../components/pages/Community.vue'
import PageBlogIndex from '../components/pages/BlogIndex.vue'

const staticRoutes = [
  { path: '/', component: PageIndex },
  { path: '/intro', component: PageIntro },
  { path: '/docs', component: PageDocs },
  { path: '/community', component: PageCommunity },
  { path: '/blog', component: PageBlogIndex }
]

let routes = staticRoutes.concat(blogRoutes)

const router = new VueRouter({
  mode: 'history',
  routes
})

export default router
