function r (page) { return require('../content/docs-' + page + '.vue') }
export default [
  { path: '/docs/changelog', component: r('changelog') },
  { path: '/docs/getting-started/first-app', component: r('getting-started-#02-first-app') },
  { path: '/docs/getting-started/deploy-testnet', component: r('getting-started-#03-deploy-testnet') },
  { path: '/docs/getting-started/next-steps', component: r('getting-started-#04-next-steps') },
  { path: '/docs/guides/abci-cli', component: r('guides-abci-cli') },
  { path: '/docs/guides/app-architecture', component: r('guides-app-architecture') },
  { path: '/docs/guides/app-development', component: r('guides-app-development') },
  { path: '/docs/guides/install-from-source', component: r('guides-install-from-source') },
  { path: '/docs/guides/using-tendermint', component: r('guides-using-tendermint') },
  { path: '/docs', component: r('index') },
  { path: '/docs/roadmap', component: r('roadmap') },
  { path: '/docs/specs/block-structure', component: r('specs-block-structure') },
  { path: '/docs/specs/byzantine-consensus-algorithm', component: r('specs-byzantine-consensus-algorithm') },
  { path: '/docs/specs/configuration', component: r('specs-configuration') },
  { path: '/docs/specs/fast-sync', component: r('specs-fast-sync') },
  { path: '/docs/specs/genesis', component: r('specs-genesis') },
  { path: '/docs/specs/light-client-protocol', component: r('specs-light-client-protocol') },
  { path: '/docs/specs/merkle', component: r('specs-merkle') },
  { path: '/docs/specs/rpc', component: r('specs-rpc') },
  { path: '/docs/specs/secure-p2p', component: r('specs-secure-p2p') },
  { path: '/docs/specs/tendermint-types', component: r('specs-tendermint-types') },
  { path: '/docs/specs/validators', component: r('specs-validators') },
  { path: '/docs/specs/wire-protocol', component: r('specs-wire-protocol') }
]
