function r (page) { return require('../content/docs/' + page + '.vue') }
export default [
  { path: '/docs/changelog', component: r('changelog') },
  { path: '/docs/guides/abci-cli', component: r('guides/abci-cli') },
  { path: '/docs/guides/app-architecture', component: r('guides/app-architecture') },
  { path: '/docs/guides/app-development', component: r('guides/app-development') },
  { path: '/docs/guides/contributing', component: r('guides/contributing') },
  { path: '/docs/guides/install-from-source', component: r('guides/install-from-source') },
  { path: '/docs/guides/install-go', component: r('guides/install-go') },
  { path: '/docs/guides/using-tendermint', component: r('guides/using-tendermint') },
  { path: '/docs', component: r('index') },
  { path: '/docs/internals/block-structure', component: r('internals/block-structure') },
  { path: '/docs/internals/byzantine-consensus-algorithm', component: r('internals/byzantine-consensus-algorithm') },
  { path: '/docs/internals/configuration', component: r('internals/configuration') },
  { path: '/docs/internals/fast-sync', component: r('internals/fast-sync') },
  { path: '/docs/internals/genesis', component: r('internals/genesis') },
  { path: '/docs/internals/light-client-protocol', component: r('internals/light-client-protocol') },
  { path: '/docs/internals/merkle', component: r('internals/merkle') },
  { path: '/docs/internals/rpc', component: r('internals/rpc') },
  { path: '/docs/internals/secure-p2p', component: r('internals/secure-p2p') },
  { path: '/docs/internals/tendermint-types', component: r('internals/tendermint-types') },
  { path: '/docs/internals/validators', component: r('internals/validators') },
  { path: '/docs/internals/wire-protocol', component: r('internals/wire-protocol') },
  { path: '/docs/roadmap', component: r('roadmap') },
  { path: '/docs/source-code', component: r('source-code') }
]
