module.exports = exports = function (post) {
  let facebookUrl = "`https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`"
  let twitterUrl = "`https://twitter.com/home?status=" + encodeURI(post.title) + "%20${window.location.href}`"

  // set up the vue file
  let f = '<!--THIS FILE IS GENERATED BY `./blog/vueTemplatePost.js` DO NOT EDIT HERE-->\n'
  f += '<template><article>\n'
  f += `<section id="section-top">`
  f += `  <div class="section-container">`
  f += `    <h1>${post.title}</h1>`
  f += `    <p>${post.dateFriendly}</p>`
  f += `  </div>`
  f += `</section>`
  f += `<section class="section-default">`
  f += `  <div class="section-container">`
  f += `    <div class="section-content">`
  f += `      <div class="article-body">`
  f +=          post.body
  f += '        <article-footer :facebook-url="facebookUrl" :twitter-url="twitterUrl"></article-footer>\n'
  f += `      </div><!--article-body-->`
  f += `      <comments></comments>`
  // f += `      <div>partial "prev_next.html"</div>`
  f += `    </div>`
  f += `  </div>`
  f += `</section>`
  f += '</article></template>\n'
  f += '<script>\n'
  f += 'import ArticleBackBtn from \'../partials/ArticleBackBtn.vue\'\n'
  f += 'import ArticleFooter from \'../partials/ArticleFooter.vue\'\n'
  f += 'import Comments from \'../partials/Comments.vue\'\n'
  f += 'export default {\n'
  f += '  components: {\n'
  f += '    ArticleBackBtn,\n'
  f += '    ArticleFooter,\n'
  f += '    Comments\n'
  f += '  },\n'
  f += '  data () {\n'
  f += '    return {\n'
  f += `      facebookUrl: ${facebookUrl},\n`
  f += `      twitterUrl: ${twitterUrl}\n`
  f += '    }\n'
  f += '  },\n'
  f += '  head: {\n'
  f += '    title: {\n'
  f += `      inner: '${post.title.replace(/'/g, "\\'")}'\n`
  f += '    }\n'
  f += '  }\n'
  f += '}\n'
  f += '</script>\n'

  return f
}
