<template>
  <!-- This file is automatically generated from `npm run docs` -->
  <!-- Edit the template at `./build/templates/TableOfContents.html` -->
  <div class="master" v-bind:class="{ 'mobile-active': isActive, 'mobile-inactive': !isActive }" @click="toggleManual">
    <nav>
  <div class="title">Getting Started</div>
  <router-link to="/download">1. Download Tendermint</router-link>
  <router-link :to="'/docs/getting-started/first-app'">2. First App</router-link>
  <router-link :to="'/docs/getting-started/deploy-testnet'">3. Deploy Testnet</router-link>
  <router-link :to="'/docs/getting-started/next-steps'">4. Next Steps</router-link>
  <router-link :to="'/docs/changelog'">Changelog</router-link>
  <router-link :to="'/docs/roadmap'">Roadmap</router-link>
  <div class="title">Guides</div>
  <router-link :to="'/docs/guides/abci-cli'">ABCI CLI</router-link>
  <router-link :to="'/docs/guides/app-architecture'">App Architecture</router-link>
  <router-link :to="'/docs/guides/app-development'">App Development</router-link>
  <router-link :to="'/docs/guides/contributing'">Contributing</router-link>
  <router-link :to="'/docs/guides/install-from-source'">Install from Source</router-link>
  <router-link :to="'/docs/guides/using-tendermint'">Using Tendermint</router-link>
</nav>
    <overlay-btns>
      <overlay-btn v-show="isActive" icon="close"></overlay-btn>
      <overlay-btn v-show="!isActive" icon="bars"></overlay-btn>
    </overlay-btns>
  </div><!--master-->
</template>

<script>
import $ from 'jquery'
import OverlayBtn from './OverlayBtn'
import OverlayBtns from './OverlayBtns'
export default {
  name: 'page-docs-master',
  components: {
    OverlayBtn,
    OverlayBtns
  },
  data () {
    return {
      isActive: false
    }
  },
  methods: {
    toggleAutomatic () {
      let self = this
      if ($(window).width() >= 768) self.isActive = true
      else self.isActive = false
    },
    toggleManual () {
      if ($(window).width() < 768) {
        this.isActive = !this.isActive
      }
    }
  },
  mounted () {
    this.toggleAutomatic()
    $(window).resize(() => this.toggleAutomatic())
  }
}
</script>
