<!--THIS FILE IS GENERATED BY `./blog/vueTemplatePost.js` DO NOT EDIT HERE-->
<template><article>
<section id="section-top">  <div class="section-container">    <h1>Tendermint: from Then to Now</h1>    <p>September 17, 2016</p>  </div></section><section class="section-default">  <div class="section-container">    <div class="section-content">      <div class="article-body"><h2>Tendermint: from Then to Now</h2>
<p>Some of you have asked about the history of <a href="http://tendermint.com/">Tendermint</a>, so here it is. Back in the day, we had some serious concerns about Bitcoin as a global currency, mainly because it is incredibly <a href="http://motherboard.vice.com/read/bitcoin-could-consume-as-much-electricity-as-denmark-by-2020">energy intensive</a>. So we started Tendermint to develop a more environmentally friendly cryptocurrency.</p>
<p>But what started as a simple cryptocurrency based on an adaptation of a <a href="http://groups.csail.mit.edu/tds/papers/Lynch/jacm88.pdf">1980’s consensus algorithm called DLS</a> eventually evolved into what it is today: a general purpose Byzantine fault tolerant (BFT) consensus algorithm for running replicated state machines over the internet in possibly adversarial conditions.</p>
<p>Replicated state machines are a staple of modern Internet technology. They permit a consistent and fault-tolerant view of some set of data. Popular open-source implementations of replicated state machines include <a href="http://bookkeeper.apache.org/">Apache ZooKeeper</a>, <a href="https://coreos.com/etcd/">CoreOS' etcd</a>, and <a href="https://www.consul.io/">Hashicorp's Consul</a>.</p>
<p>In each of these, the state machine is a simple key-value store, and the underlying consensus algorithm is either Paxos or <a href="https://raft.github.io/">Raft</a>. Neither of these algorithms tolerate even a single malicious node in the system. You can see an animation of the Paxos algorithm <a href="http://harry.me/blog/2014/12/27/neat-algorithms-paxos/">here</a>.</p>
<p>In contrast, Tendermint lets you build arbitrary state machines in any programming language, whether that is a key-value store in Go, a voting system in C++, or a cryptocurrency in OCaml. In each case, the application implements a simple interface, and Tendermint handles the rest, including connecting to peers, syncing the latest state, gossipping transactions, and maintaining a consistent log of transactions.</p>
<h2>Who is using Tendermint?</h2>
<p>It’s been an exciting journey, and over the past few months people have been putting Tendermint to work in several applications.</p>
<p>Probably the most complicated implementation of Tendermint so far is by Eris Industries. Eris is using Tendermint to power its <a href="https://erisindustries.com/components/erisdb/">eris:db</a> blockchain client. Eris:db includes a fully compatible Ethereum virtual machine and other features that make it a full-fledged blockchain.</p>
<p>But there are other implementations. <a href="http://www.cloudsoft.io/">CloudSoft</a> published a <a href="http://www.cloudsoft.io/tendermint-and-clocker/">deployment strategy</a> for Apache Brooklyn that uses Tendermint and Clocker. Martin Dyring wrote an <a href="https://github.com/mdyring/cpp-tmsp">implementation of Tendermint TMSP in C++</a>, and wolfposd wrote a <a href="https://github.com/wolfposd/TMChat">chatroom app in Java</a> that uses Tendermint to broadcast messages from one user to another. Yes, that’s right, a chatroom.</p>
<p>While it might sound crazy to run a chat application on a blockchain, this is simply an example of the flexibility of Tendermint. This sort of implementation might even come in handy in instances where you have several actors who are malicious and maintaining the total order of the system matters, for instance, in p2p gaming.</p>
<p>Other companies building on Tendermint include <a href="https://blockfreight.com/">Blockfreight</a>, <a href="http://www.vidroll.com/">Vidroll</a>, and <a href="https://stratumn.com/">Stratumn</a> to name a few. Of course, we use Tendermint too. Our first product built on Tendermint is <a href="http://cosmos.network/">Cosmos, the internet of blockchains</a>.</p>
<h2>What’s new?</h2>
<p>In August 2016, we released Tendermint v0.7.0, the first stable release of our middleware. It featured a weakly-synchronous BFT consensus algorithm, which can process thousands of transactions per second with latencies on the order of a second and cluster sizes ranging from 4 to 64 nodes.</p>
<p>Recently we released <a href="https://github.com/tendermint/tendermint">Tendermint v0.7.1</a>, which includes a variety of fixes, as well as the ability for applications to determine what peers Tendermint can connect to and filtering either by IP address, or by public key.</p>
<p>In the next major release, Tendermint v0.8.0, which should be in October, we plan to introduce a handshake between Tendermint and whatever application is using it, ensuring the two stay synced even after crashes and restarts.</p>
<p>Additionally, we’ll include some important fixes to the BFT consensus module. While testing Tendermint in adversarial conditions, we discovered a Byzantine node could potentially halt the system in some circumstances—this fix will prevent that from happening.</p>
<p>This is critical because even though the Tendermint consensus algorithm guarantees your blockchain won't fork, all of the subcomponents need to work perfectly to ensure liveness.</p>
<p>Stay tuned for more updates. We are continuing to test Tendermint extensively in a push to provide a production ready offering in early 2017. And, if you are using Tendermint in a project, <a href="https://docs.google.com/a/tendermint.com/forms/d/e/1FAIpQLSclH87WiZrer8aUzO5oNWoSCqcbn4mwQ3sDJJX44E9rhdVJFw/viewform?c=0&amp;w=1">let us know</a>! We want to hear how you’re using it and what your feedback is.</p>
        <article-footer :facebook-url="facebookUrl" :twitter-url="twitterUrl"></article-footer>
      </div><!--article-body-->      <comments></comments>    </div>  </div></section></article></template>
<script>
import ArticleBackBtn from '../partials/ArticleBackBtn.vue'
import ArticleFooter from '../partials/ArticleFooter.vue'
import Comments from '../partials/Comments.vue'
export default {
  components: {
    ArticleBackBtn,
    ArticleFooter,
    Comments
  },
  data () {
    return {
      facebookUrl: `https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`,
      twitterUrl: `https://twitter.com/home?status=Tendermint:%20from%20Then%20to%20Now%20${window.location.href}`
    }
  },
  head: {
    title: {
      inner: 'Tendermint: from Then to Now'
    }
  }
}
</script>
