<!--THIS FILE IS GENERATED BY `./blog/vueTemplatePost.js` DO NOT EDIT HERE-->
<template><article>
  <article-back-btn></article-back-btn>
  <div class="header-padding"></div>
  <div class="article-wrapper">
    <h1>Tendermint vs PBFT</h1>

    <div class="subtitle">October 3, 2015</div>

<p>Tendermint was originally inspired by the DLS algorithm (<a href="http://groups.csail.mit.edu/tds/papers/Lynch/jacm88.pdf">link</a>).  After several iterations to improve efficiency, (namely, making it more asynchronous), it has become quite similar to the PBFT algorithm (<a href="http://www.pmg.lcs.mit.edu/papers/osdi99.pdf">link</a>).  This document serves to illustrate the similarities and differences between Tendermint and PBFT.</p>
<p>|Tendermint     | PBFT              |
|</p>
    <article-footer :facebook-url="facebookUrl" :twitter-url="twitterUrl"></article-footer>
  </div><!--article-wrapper-->
</article></template>
<script>
import ArticleBackBtn from '../partials/ArticleBackBtn.vue'
import ArticleFooter from '../partials/ArticleFooter.vue'
export default {
  components: {
    ArticleBackBtn,
    ArticleFooter
  },
  data () {
    return {
      facebookUrl: `https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`,
      twitterUrl: `https://twitter.com/home?status=Tendermint%20vs%20PBFT%20${window.location.href}`
    }
  },
  head: {
    title: {
      inner: 'Tendermint vs PBFT'
    }
  }
}
</script>
