<!--THIS FILE IS GENERATED BY `./blog/vueTemplatePost.js` DO NOT EDIT HERE-->
<template><article>
  <article-back-btn></article-back-btn>
  <div class="header-padding"></div>
  <div class="article-wrapper">
    <h1>TMSP: The Tendermint Socket Protocol</h1>

    <div class="subtitle">December 19, 2015</div>

<blockquote>
<p>&lt;p&gt;After you read this post, don't forget to check out our tutorials!  They also appear at the end of this page.&lt;/p&gt;</p>
</blockquote>
<blockquote>
<ol>
<li><a href="/tutorials/run-your-first-tmsp-application/">Run your first TMSP application</a></li>
<li><a href="/tutorials/launch-a-tmsp-testnet/">Launch a TMSP testnet</a></li>
</ol>
</blockquote>
<h2>Motivation</h2>
<p>Thus far, all blockchains &quot;stacks&quot; (such as <a href="https://github.com/bitcoin/bitcoin">Bitcoin</a>) have had a monolithic design.  That is, each blockchain stack is a single program that handles all the concerns of a decentralized ledger; this includes P2P connectivity, the &quot;mempool&quot; broadcasting of transactions, consensus on the most recent block, account balances, Turing-complete contracts, user-level permissions, etc.</p>
<p>This approach to blockchain development has several problems.  First, creating a new blockchain requires forking an existing blockchain stack, and this comes with the cost of complexity.  First you need to understand all the components of a blockchain stack, even those that aren't directly relevant to the logic of your application.  This is especially true when the codebase is not modular in design and suffers from &quot;spaghetti code&quot;.</p>
<p>Another problem with this approach is that it limits you to the language of the blockchain stack (or vice versa).  In the case of Ethereum which supports a Turing-complete bytecode virtual-machine, it limits you to languages that compile down to that bytecode; today, those are Serpent and Solidity.</p>
<p>In contrast, our approach is to decouple the consensus engine and P2P layers from the details of the application state of the particular blockchain application.</p>
<h2>Intro to TMSP</h2>
<p><a href="https://github.com/tendermint/tendermint">Tendermint Core</a> (the &quot;consensus engine&quot;) speaks to the application via a socket protocol called <a href="https://github.com/tendermint/tmsp">TMSP</a>.</p>
<p>To draw an analogy, lets talk about a well-known cryptocurrency, Bitcoin.  Bitcoin is a cryptocurrency blockchain where each node maintains a fully audited Unspent Transaction Output (UTXO) database. If one wanted to create a Bitcoin-like system on top of TMSP, Tendermint Core would be responsible for</p>
<ul>
<li>Sharing blocks and transactions between nodes</li>
<li>Establishing a canonical/immutable order of transactions (the blockchain)</li>
</ul>
<p>The application will be responsible for</p>
<ul>
<li>Maintaining the UTXO database</li>
<li>Validating cryptographic signatures of transactions</li>
<li>Preventing transactions from spending non-existent transactions</li>
<li>Allowing clients to query the UTXO database.</li>
</ul>
<p>Tendermint is able to decompose the blockchain design by offering a very simple API between the application process and consensus process.</p>
<p>The API consists of 3 primary message types that get delivered from the core to the application.  The application replies with corresponding response messages.</p>
<p>The messages are specified here: https://github.com/tendermint/tmsp#message-types</p>
<p>The <code>AppendTx</code> message is the work horse of the application.  Each transaction in the blockchain is delivered with this message. The application needs to validate each transactions received with the <code>AppendTx</code> message against the current state, application protocol, and the cryptographic credentials of the transaction. A validated transaction then needs to update the application state — by binding a value into a key values store, or by updating the UTXO database.</p>
<p>The <code>CheckTx</code> message is similar to <code>AppendTx</code>, but it's only for validating transactions.  Tendermint Core's mempool first checks the validity of a transaction with <code>CheckTx</code>, and only relays valid transactions to its peers.  Applications may check an incrementing nonce in the transaction and return an error upon <code>CheckTx</code> if the nonce is old.</p>
<p>The <code>Commit</code> message is used to compute a cryptographic commitment to the current application state, to be placed into the next block header. This has some handy properties. Inconsistencies in updating that state will now appear as blockchain forks which catches a whole class of programming errors. This also simplifies the development of secure lightweight clients, as Merkle-hash proofs can be verified by checking against the block hash, and the block hash is signed by a quorum of validators.</p>
<p>There can be multiple TMSP socket connections to an application.  Tendermint Core creates two TMSP connections to the application; one for the validation of transactions when broadcasting in the mempool, and another for the consensus engine to run block proposals.</p>
<p>It's probably evident that applications designers need to very carefully design their message handlers to create a blockchain that does anything useful but this architecture provides a place to start.</p>
<h2>A Note on Determinism</h2>
<p>The logic for blockchain transaction processing must be deterministic.  If the application logic weren't deterministic, consensus would not be reached among the Tendermint Core replica nodes.</p>
<p>Solidity on Ethereum is a great language of choice for blockchain applications because, among other reasons, it is a completely deterministic programming language.  However, it's also possible to create deterministic applications using existing popular languages like Java, C++, Python, or Go.  Game programmers and blockchain developers are already familiar with creating deterministic programs by avoiding sources of non-determinism such as:</p>
<ul>
<li>random number generators (without deterministic seeding)</li>
<li>race conditions on threads (or avoiding threads altogether)</li>
<li>the system clock</li>
<li>uninitialized memory (in unsafe programming languages like C or C++)</li>
<li><a href="http://gafferongames.com/networking-for-game-programmers/floating-point-determinism/">floating point arithmetic</a></li>
<li>language features that are random (e.g. map iteration in Go)</li>
</ul>
<p>While programmers can avoid non-determinism by being careful, it is also possible to create a special linter or static analyzer for each language to check for determinism.  In the future we may work with partners to create such tools.</p>
<h2>Tutorials</h2>
<p>Follow these tutorials to quickly get started developing your TMSP application.</p>
<ul>
<li><a href="/tutorials/run-your-first-tmsp-application/">Run your first TMSP application</a></li>
<li><a href="/tutorials/launch-a-tmsp-testnet/">Launch a TMSP testnet</a></li>
</ul>
<h2>Contributions</h2>
<p><em>Many thanks to Zaki Manian for providing the &quot;Intro to TMSP&quot; section</em></p>
    <article-footer :facebook-url="facebookUrl" :twitter-url="twitterUrl"></article-footer>
  </div><!--article-wrapper-->
</article></template>
<script>
import ArticleBackBtn from '../partials/ArticleBackBtn.vue'
import ArticleFooter from '../partials/ArticleFooter.vue'
export default {
  components: {
    ArticleBackBtn,
    ArticleFooter
  },
  data () {
    return {
      facebookUrl: `https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`,
      twitterUrl: `https://twitter.com/home?status=TMSP:%20The%20Tendermint%20Socket%20Protocol%20${window.location.href}`
    }
  },
  head: {
    title: {
      inner: 'TMSP: The Tendermint Socket Protocol'
    }
  }
}
</script>
